### ISSUE TITLE
git clone recursive ONNF failed

### ISSUE THREAD

**Issue by jacky82226** [clang-ykt/ONNF#111]
While I tried to git clone ONNF recursively, 
`git clone --recursive git@github.com:clang-ykt/ONNF.git`
I bumped into an error which is

> Cloning into '/mypath/ONNF/third_party/variant'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mpark/variant.git' into submodule path '/mypath/ONNF/third_party/variant' failed
Failed to clone 'third_party/variant'. Retry scheduled
Cloning into '/mypath/ONNF/third_party/variant'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

I could successfully git clone recursively benchmark, pybind11 and onnx except variant. It said that I have no permission to access it but it is a public repo. I was wondering that is this link (variant) valid or I need to set something for it?

Thank you!

**Comment by doru1004** [comment]
The project has been moved recently. It has also changed name from ONNF to onnx-mlir. The link to the latest version of this project is here:

https://github.com/onnx/onnx-mlir

Thanks.
