### ISSUE TITLE
[RFC] Reorganize code for the lower-frontend pass.

### ISSUE THREAD

**Issue by tungld** [clang-ykt/ONNF#24]
Given that the current source code file for the `lower-frontend` pass is big and is becoming bigger, and we are using a singe file for the pass, it is better to put lowering parts for different categories of operators (e.g, Pointwise, Conv, Norm, etc.) into different include files. 

For examples, we will have the following include files:
- `lower_frontend_to_krnl_pointwise.inc` for lowering all pointwise/elementwise ONNX operators
- `lower_frontend_to_krnl_conv.inc` for lowing convolution operators
- `lower_frontend_to_krnl_matmul.inc` for lowing the matmul operator.

Those include file will be included in the main lowering pass file `lower_frontend_to_krnl.cpp`

**Comment by tjingrant** [comment]
Hi @tungld . ONNX already put operations into several categories (c.f. https://github.com/onnx/onnx/tree/master/onnx/defs). Do you think this existing taxonomy is a good place to start? Or do you think dividing them into finer categories is needed?

**Comment by tungld** [comment]
Yes, it is definitely a good place to start. We will categorize as closely as possible to the ONNX taxonomy. From user's point of view, it is a good taxonomy since it is easy to understand. But from developer's point of view, we would also like to group operators with the same pattern of computation into the same group.

For example, the `reduction` category in the ONNX taxonomy seems to meet the both requirements. However, point-wise operators are scattered into logical and math categories (e.g. And, Or, Xor, Not are in the logical one, while Abs, Sort, Relu are in the math one). In this case, we will classify them into a point-wise category, and might add additional information to say that they are logical or math operators.

**Comment by tungld** [comment]
Created a prototype: #30.

**Comment by tjingrant** [comment]
@tungld any update? It seems like the earlier we pursue this proposal, the less painful it would be for our future work. Please let me know if there's anything I can help!

**Comment by tungld** [comment]
I already created a draft in PR #30. We then decided to split it into smaller ones. Being said that, I will have two PRs: one of them is #61, the other one to follow the ONNX taxonomy will be open soon.
