### ISSUE TITLE
KrnlEntryPoint for scalar operands

### ISSUE THREAD

**Issue by tungld** [clang-ykt/ONNF#47]
@tjingrant need your help on the following issue, it is possibly related to KrnlEntryPoint lowering.

I am working with Gemm. Currently there are two backend tests failed: `test_gemm_default_no_bias_cpu` and `test_gemm_default_scalar_bias_cpu`. I know the former one is related to optional operands. But for the latter one I don't know why it failed and need your help. So let me reproduce the problem by a simple example

I used the following command: `onnf-opt --lower-all-llvm krnl.mlir`

The program `krnl.mlir` is:
```mlir
module {                                                                                                                  
func @main_graph(%arg0: memref<f32>) -> memref<f32> {
    %0 = alloc() : memref<f32>
    %1 = load %arg0[] : memref<f32>
    store %1, %0[] : memref<f32>
    return %0 : memref<f32>
  }
}
```
The above code worked well, we got an output in LLVM.

However, when I added a `krnl.entry_point` as follows:
```mlir
module {                                                                                                                  
func @main_graph(%arg0: memref<f32>) -> memref<f32> {
    %0 = alloc() : memref<f32>
    %1 = load %arg0[] : memref<f32>
    store %1, %0[] : memref<f32>
    return %0 : memref<f32>
  }
  "krnl.entry_point"() {func = @main_graph, numInputs = 1 : i32, numOutputs = 1 : i32} : () -> ()
}
```

I got the following error (similar to what I got for the Gemm test):
```
/home/tungld/dl/llvm-project/llvm/include/llvm/IR/DerivedTypes.h:352: llvm::Type* llvm::StructType::getElement
Type(unsigned int) const: Assertion `N < NumContainedTys && "Element number out of range!"' failed.
```

**Comment by tjingrant** [comment]
@tungld sorry for the dealyed reply. I have a rough idea of why this assertion failure occurs (Scalar MemRef lowers to a LLVM struct that's kind of unique). I will take a look soon.
