### ISSUE TITLE
Question about KRNL

### ISSUE THREAD

**Issue by Zehaos** [clang-ykt/ONNF#77]
There are two dialect in ONNF, onnx and krnl. ONNX dialect is straight forward, but I don't know what is krnl used for? Could you shred light on it? Thanks in advance.

**Comment by tjingrant** [comment]
@Zehaos krnl dialect is an intermediate step we go through between ONNX and Affine (and in the future, StructuredOps) dialect. A user of our infrastructure interested in going from ONNX -> MLIR existing dialects would not care about its existence.

I understand that this would be a burden to learn if one is interested in contributing, and we are looking at various options to make it easier for outside contributors to modify/contribute/instrument ONNF, and I would certainly appreciate your input!

**Comment by Zehaos** [comment]
@tjingrant Thank you for your answer!
